version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: smart_budget_postgres
    environment:
      POSTGRES_DB: smart_budget
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: src/test/java
    container_name: smart_budget_backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/smart_budget
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET: super-secret-jwt-generation-key-228-123456789101112

volumes:
  postgres_data: