spring.application.name=smart-budget

# Подключение к PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/smart_budget
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA настройки
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT секрет (минимум 32 символа = 256 бит)
jwt.secret=mySuperSecretKeyForJWTThatIsAtLeast256BitsLong1234567890
jwt.expiration-hours=10
